name: datum_hive
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  datum:
    path: ../datum/
  flutter:
    sdk: flutter
  hive_ce_flutter: ^2.3.3
  meta: ^1.16.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.0

dependency_overrides:
  test_api: ^0.7.7

flutter:
