// GENERATED CODE - DO NOT MODIFY BY HAND
// Consider adding this file to your .gitignore.

import 'package:test/test.dart';

import 'unit/datum_logger_test.dart' as _a;
import 'unit/query_test.dart' as _b;
import 'unit/hash_generator_test.dart' as _c;
import 'core/datum_sync_operation_test.dart' as _d;
import 'core/sync_engine_test.dart' as _e;
import 'core/datum_health_test.dart' as _f;
import 'core/isolate_helper_test.dart' as _g;
import 'core/user_switch_test.dart' as _h;
import 'core/datum_sync_conflict_summary_test.dart' as _i;
import 'core/sync_manager_external_change_test.dart' as _j;
import 'core/relational_data_test.dart' as _k;
import 'core/datum_pagination_test.dart' as _l;
import 'core/local_adapter_watch_storage_size_test.dart' as _m;
import 'core/datum_sync_result_test.dart' as _n;
import 'core/datum_manager_lifecycle_test.dart' as _o;
import 'core/datum_sync_options_test.dart' as _p;
import 'core/error_strategy_test.dart' as _q;
import 'core/user_switch_models_test.dart' as _r;
import 'core/adapter_test.dart' as _s;
import 'core/datum_sync_status_snapshot_test.dart' as _t;
import 'core/middleware_test.dart' as _u;
import 'core/datum_metrics_model_test.dart' as _v;
import 'core/queue_manager_test.dart' as _w;
import 'core/datum_config_test.dart' as _x;
import 'core/datum_sync_statistics_test.dart' as _y;
import 'core/sync_execution_strategy_test.dart' as _z;
import 'core/datum_change_detail_test.dart' as _A;
import 'core/datum_core_test.dart' as _B;
import 'core/conflict_detector_test.dart' as _C;
import 'core/datum_index_config_test.dart' as _D;
import 'core/datum_exception_test.dart' as _E;
import 'core/datum_sync_scope_test.dart' as _F;
import 'core/sync_strategy_integration_test.dart' as _G;
import 'core/datum_metrics_test.dart' as _H;
import 'core/sync_manager_test.dart' as _I;
import 'core/auto_start_sync_test.dart' as _J;
import 'core/datum_facade_integration_test.dart' as _K;
import 'core/datum_observer_test.dart' as _L;
import 'core/sync_metadata_test.dart' as _M;
import 'core/datum_health_integration_test.dart' as _N;
import 'integration/sync_event_test.dart' as _O;
import 'integration/observer_integration_test.dart' as _P;
import 'integration/reactive_relational_data_integration_test.dart' as _Q;
import 'integration/sync_manager_integration_test.dart' as _R;
import 'integration/datum_sync_result_test.dart' as _S;
import 'integration/reactive_qureries_integration_test.dart' as _T;
import 'integration/conflict_resolution_integration_test.dart' as _U;
import 'integration/datum_sync_scope_integration_test.dart' as _V;
import 'integration/sequential_request_integration_test.dart' as _W;
import 'integration/excludable_entity_test.dart' as _X;
import 'integration/data_sync_integration_test.dart' as _Y;
import 'integration/migration_integration_test.dart' as _Z;
import 'integration/user_switch_integration_test.dart' as _aa;
import 'integration/relational_data_integration_test.dart' as _ba;
import 'integration/advance_sync_integration_test.dart' as _ca;
import 'resolver/conflict_resolver_test.dart' as _da;

void main() {

  group('unit/datum_logger_test.dart', () { _a.main(); });
  group('unit/query_test.dart', () { _b.main(); });
  group('unit/hash_generator_test.dart', () { _c.main(); });
  group('core/datum_sync_operation_test.dart', () { _d.main(); });
  group('core/sync_engine_test.dart', () { _e.main(); });
  group('core/datum_health_test.dart', () { _f.main(); });
  group('core/isolate_helper_test.dart', () { _g.main(); });
  group('core/user_switch_test.dart', () { _h.main(); });
  group('core/datum_sync_conflict_summary_test.dart', () { _i.main(); });
  group('core/sync_manager_external_change_test.dart', () { _j.main(); });
  group('core/relational_data_test.dart', () { _k.main(); });
  group('core/datum_pagination_test.dart', () { _l.main(); });
  group('core/local_adapter_watch_storage_size_test.dart', () { _m.main(); });
  group('core/datum_sync_result_test.dart', () { _n.main(); });
  group('core/datum_manager_lifecycle_test.dart', () { _o.main(); });
  group('core/datum_sync_options_test.dart', () { _p.main(); });
  group('core/error_strategy_test.dart', () { _q.main(); });
  group('core/user_switch_models_test.dart', () { _r.main(); });
  group('core/adapter_test.dart', () { _s.main(); });
  group('core/datum_sync_status_snapshot_test.dart', () { _t.main(); });
  group('core/middleware_test.dart', () { _u.main(); });
  group('core/datum_metrics_model_test.dart', () { _v.main(); });
  group('core/queue_manager_test.dart', () { _w.main(); });
  group('core/datum_config_test.dart', () { _x.main(); });
  group('core/datum_sync_statistics_test.dart', () { _y.main(); });
  group('core/sync_execution_strategy_test.dart', () { _z.main(); });
  group('core/datum_change_detail_test.dart', () { _A.main(); });
  group('core/datum_core_test.dart', () { _B.main(); });
  group('core/conflict_detector_test.dart', () { _C.main(); });
  group('core/datum_index_config_test.dart', () { _D.main(); });
  group('core/datum_exception_test.dart', () { _E.main(); });
  group('core/datum_sync_scope_test.dart', () { _F.main(); });
  group('core/sync_strategy_integration_test.dart', () { _G.main(); });
  group('core/datum_metrics_test.dart', () { _H.main(); });
  group('core/sync_manager_test.dart', () { _I.main(); });
  group('core/auto_start_sync_test.dart', () { _J.main(); });
  group('core/datum_facade_integration_test.dart', () { _K.main(); });
  group('core/datum_observer_test.dart', () { _L.main(); });
  group('core/sync_metadata_test.dart', () { _M.main(); });
  group('core/datum_health_integration_test.dart', () { _N.main(); });
  group('integration/sync_event_test.dart', () { _O.main(); });
  group('integration/observer_integration_test.dart', () { _P.main(); });
  group('integration/reactive_relational_data_integration_test.dart', () { _Q.main(); });
  group('integration/sync_manager_integration_test.dart', () { _R.main(); });
  group('integration/datum_sync_result_test.dart', () { _S.main(); });
  group('integration/reactive_qureries_integration_test.dart', () { _T.main(); });
  group('integration/conflict_resolution_integration_test.dart', () { _U.main(); });
  group('integration/datum_sync_scope_integration_test.dart', () { _V.main(); });
  group('integration/sequential_request_integration_test.dart', () { _W.main(); });
  group('integration/excludable_entity_test.dart', () { _X.main(); });
  group('integration/data_sync_integration_test.dart', () { _Y.main(); });
  group('integration/migration_integration_test.dart', () { _Z.main(); });
  group('integration/user_switch_integration_test.dart', () { _aa.main(); });
  group('integration/relational_data_integration_test.dart', () { _ba.main(); });
  group('integration/advance_sync_integration_test.dart', () { _ca.main(); });
  group('resolver/conflict_resolver_test.dart', () { _da.main(); });
}

